let exper = [
  {
    date: "June 2022 - dec 2022",
    company: "Google",
    role: "Full Stack Developer",
    description: [
      "Developed scalable web applications using React, Node.js, and MongoDB.",
      "Collaborated with cross-functional teams to implement cloud-based microservices using AWS.",
      "Enhanced system performance by optimizing RESTful APIs, reducing latency by 25%.",
    ],
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg",
    Technologies: [
      "Python",
      "Django",
      "Django Channels",
      "Apache Kafka",
      "PostgreSQL",
      "REST APIs",
      "Docker",
      "Git",
      "Celery",
      "Redis",
    ],
    "b-color": "white",
  },
  {
    date: "Jan 202 - April 2022",
    company: "SilwerWings Technologies Pvt Ltd",
    role: "Software Engineer intern",
    description: [
      "Led the development of a real-time data processing platform using Python Django and Channels.",
      "Improved database efficiency by restructuring queries and indexing, resulting in a 40% reduction in query time.",
      "Collaborated closely with the product team to refine application features and enhance user experience.",
    ],
    Technologies: [
      "Python",
      "Django",
      "Django Channels",
      "Apache Kafka",
      "PostgreSQL",
      "REST APIs",
      "Docker",
      "Git",
      "Celery",
      "Redis",
    ],
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/51/Facebook_f_logo_%282019%29.svg",
    "b-color": "blue",
  },
  {
    date: "January 2021 - dec 2021",
    company: "LinkedIn",
    role: "Backend Developer",
    description: [
      "Designed and maintained secure, high-performance APIs using Python and Django.",
      "Implemented role-based access control (RBAC) to secure the company's internal systems.",
      "Collaborated on the migration of legacy systems to a cloud infrastructure using Google Cloud.",
    ],
    Technologies: [
      "Python",
      "Django",
      "Django Channels",
      "Apache Kafka",
      "PostgreSQL",
      "REST APIs",
      "Docker",
      "Git",
      "Celery",
      "Redis",
    ],
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg",
    "b-color": "red",
  },
];

export default exper;
