import Unnati from "../assets/Unnatilogo.jpeg";
let exper = [
  {
    date: "Jan 2022 - April 2022",
    company: "SilwerWings Technologies Pvt Ltd",
    role: "Software Engineer intern",
    description: [
      "Led the development of a real-time data processing platform using Python Django and Channels.",
      "Improved database efficiency by restructuring queries and indexing, resulting in a 40% reduction in query time.",
      "Collaborated closely with the product team to refine application features and enhance user experience.",
    ],
    Technologies: [
      "Python",
      "Django",
      "Django Channels",
      "Apache Kafka",
      "PostgreSQL",
      "REST APIs",
      "Docker",
      "Git",
      "Celery",
      "Redis",
    ],
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/51/Facebook_f_logo_%282019%29.svg",
    "b-color": "blue",
  },
  {
    date: "June 2022 - dec 2022",
    company: "Unnati Informatics LLP",
    role: "Software Engineering - QA Tester",
    description: [
      "Conducted comprehensive testing of web applications developed with React, Node.js, and MongoDB to ensure functionality and performance.",
      "Collaborated with cross-functional teams to validate cloud-based microservices implemented on AWS, ensuring quality and compliance with requirements.",
      "Improved system reliability by optimizing test cases for RESTful APIs, leading to a 25% reduction in identified latency issues.",
    ],
    logo: `${Unnati}`,
    Technologies: [
      "Java",
      "JUnit",
      "Mockito",
      "Selenium",
      "Postman",
      "Git",
      "Docker",
      "REST APIs",
      "TestNG",
      "JIRA",
    ],
    "b-color": "white",
  },
  {
    date: "January 2021 - dec 2021",
    company: "LinkedIn",
    role: "Backend Developer",
    description: [
      "Designed and maintained secure, high-performance APIs using Python and Django.",
      "Implemented role-based access control (RBAC) to secure the company's internal systems.",
      "Collaborated on the migration of legacy systems to a cloud infrastructure using Google Cloud.",
    ],
    Technologies: [
      "Python",
      "Django",
      "Django Channels",
      "Apache Kafka",
      "PostgreSQL",
      "REST APIs",
      "Docker",
      "Git",
      "Celery",
      "Redis",
    ],
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg",
    "b-color": "red",
  },
];

export default exper;
